ALTER TABLE "permisos" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "permisos_especiales_por_rol" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "permisos_especiales_por_usuario" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sucursales" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tenants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "usuarios" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "permisos_tenant_select" ON "permisos" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("permisos"."rol_id" in (select id from roles where tenant_id = (select current_tenant_id()) or tenant_id is null));--> statement-breakpoint
CREATE POLICY "permisos_tenant_modify" ON "permisos" AS PERMISSIVE FOR ALL TO "authenticated" USING ("permisos"."rol_id" in (select id from roles where tenant_id = (select current_tenant_id()) or tenant_id is null)) WITH CHECK ("permisos"."rol_id" in (select id from roles where tenant_id = (select current_tenant_id()) or tenant_id is null));--> statement-breakpoint
CREATE POLICY "permisos_especiales_por_rol_tenant_select" ON "permisos_especiales_por_rol" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("permisos_especiales_por_rol"."rol_id" in (select id from roles where tenant_id = (select current_tenant_id()) or tenant_id is null));--> statement-breakpoint
CREATE POLICY "permisos_especiales_por_rol_tenant_modify" ON "permisos_especiales_por_rol" AS PERMISSIVE FOR ALL TO "authenticated" USING ("permisos_especiales_por_rol"."rol_id" in (select id from roles where tenant_id = (select current_tenant_id()) or tenant_id is null)) WITH CHECK ("permisos_especiales_por_rol"."rol_id" in (select id from roles where tenant_id = (select current_tenant_id()) or tenant_id is null));--> statement-breakpoint
CREATE POLICY "permisos_especiales_por_usuario_tenant_select" ON "permisos_especiales_por_usuario" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("permisos_especiales_por_usuario"."usuario_id" in (select id from usuarios where tenant_id = (select current_tenant_id())));--> statement-breakpoint
CREATE POLICY "permisos_especiales_por_usuario_tenant_modify" ON "permisos_especiales_por_usuario" AS PERMISSIVE FOR ALL TO "authenticated" USING ("permisos_especiales_por_usuario"."usuario_id" in (select id from usuarios where tenant_id = (select current_tenant_id()))) WITH CHECK ("permisos_especiales_por_usuario"."usuario_id" in (select id from usuarios where tenant_id = (select current_tenant_id())));--> statement-breakpoint
CREATE POLICY "roles_tenant_select" ON "roles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("roles"."tenant_id" = (select current_tenant_id()) or "roles"."tenant_id" is null);--> statement-breakpoint
CREATE POLICY "roles_tenant_modify" ON "roles" AS PERMISSIVE FOR ALL TO "authenticated" USING ("roles"."tenant_id" = (select current_tenant_id()) or "roles"."tenant_id" is null) WITH CHECK ("roles"."tenant_id" = (select current_tenant_id()) or "roles"."tenant_id" is null);--> statement-breakpoint
CREATE POLICY "sucursales_tenant_select" ON "sucursales" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("sucursales"."tenant_id" = (select current_tenant_id()));--> statement-breakpoint
CREATE POLICY "sucursales_tenant_modify" ON "sucursales" AS PERMISSIVE FOR ALL TO "authenticated" USING ("sucursales"."tenant_id" = (select current_tenant_id())) WITH CHECK ("sucursales"."tenant_id" = (select current_tenant_id()));--> statement-breakpoint
CREATE POLICY "tenants_tenant_select" ON "tenants" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("tenants"."id" = (select current_tenant_id()));--> statement-breakpoint
CREATE POLICY "tenants_tenant_modify" ON "tenants" AS PERMISSIVE FOR ALL TO "authenticated" USING ("tenants"."id" = (select current_tenant_id())) WITH CHECK ("tenants"."id" = (select current_tenant_id()));--> statement-breakpoint
CREATE POLICY "usuarios_tenant_select" ON "usuarios" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("usuarios"."tenant_id" = (select current_tenant_id()));--> statement-breakpoint
CREATE POLICY "usuarios_tenant_modify" ON "usuarios" AS PERMISSIVE FOR ALL TO "authenticated" USING ("usuarios"."tenant_id" = (select current_tenant_id())) WITH CHECK ("usuarios"."tenant_id" = (select current_tenant_id()));